#!/bin/bash
PKG_NAME=apache-livy

CWD="$(cd "$(dirname "${0}")" && pwd -P)"
CMD="$(basename "${0}")"

export LIVY_HOME="$(cd "$CWD/../share/$PKG_NAME" && pwd -P)"

echo -e ""
echo -e "Setting up LIVY_HOME to \${LIVY_HOME} ..."
if [[ -z \${@} ]]; then
    echo -e "Launching $CMD"
    echo -e ""
    $LIVY_HOME/bin/$CMD
else
    echo -e "Launching $CMD \"${@}\""
    echo -e ""
    $LIVY_HOME/bin/$CMD "${@}"
fi
