name: root

channels:
  - http://repo.continuum.io/pkgs/free
  - http://conda.anaconda.org/conda-forge/linux-64
  - http://conda.anaconda.org/danielfrg

dependencies:
  # - anaconda
  - pyspark
  # - nltk-with-data
  # - spacy
  # - spacy-en_core_web_sm
  # - spacy-es_core_web_md
  # - apache-livy
  # - r
  # - r-essentials
