{%set name = "scala" %}
{%set version = "2.11.8" %}
{%set hash_type = "sha256" %}
{%set hash_val = "87fc86a19d9725edb5fd9866c5ee9424cdb2cd86b767f1bb7d47313e8e391ace" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: http://downloads.lightbend.com/scala/{{ version }}/scala-{{ version }}.tgz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk
  run:
    - openjdk

test:
  commands:
    - scalac -help

about:
  home: http://www.scala-lang.org/
  license: 3-clause BSD license
  summary: Scala - Object-Oriented Meets Functional
