{%set name = "nltk" %}
{%set version = "3.2.4" %}
{%set hash_type = "sha256" %}
{%set hash_val = "8682ae52f5de4f2ba7b77bd78222a38575ad01ef29946214b254dfdf93a3a0eb" %}

package:
  name: {{ name }}-with-data
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    # Add conda PREFIX to where NLTK searches for data
    - data.py.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - nltk
  files:
    - test_data.py
  commands:
    - python test_data.py
